'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはテンプレートから生成されました。
'
'     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
'     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class SampleAppDBEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=SampleAppDBEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property M_メーカー() As DbSet(Of M_メーカー)
    Public Overridable Property M_商品分類() As DbSet(Of M_商品分類)
    Public Overridable Property T_適用価格() As DbSet(Of T_適用価格)
    Public Overridable Property M_商品() As DbSet(Of M_商品)

End Class
