'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはテンプレートから生成されました。
'
'     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
'     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class M_商品
    Public Property 商品ID As String
    Public Property メーカー As Integer
    Public Property 商品名 As String
    Public Property 分類 As Integer
    Public Property 単位 As Integer
    Public Property 仕入価格 As Decimal
    Public Property 販売価格 As Decimal

End Class
